Algoritmo "semnome"
// Pergunte um numero ao usuario e informe se este numero e par ou impar
Var
// Seção de Declarações das variáveis

numero: inteiro
situacao: caracter



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero:")
leia(numero)

resto <- num % 2

se( resto = 0) entao
    escreva(numero, "E par")
    
senao
     escreval(numero, "E impar")
     
fimse


Fimalgoritmo